@startuml Paperboy

class Jugador
enum Juego

class Paperboy
class Habilidad
class Velocidad
class Lanzar
class TocarObstaculo
class Puntos
class Vida


class Sonido
class Obstaculo
class Nivel
class Calle
class Buzon
class Persona
class Alcantarilla
class Ventana
class Perro
class Charco
class Casa

class Item
class Periodico

Persona o-- Juego
Juego "1" *-- "1" Jugador
Jugador "1" o-- "1" Paperboy
Jugador "1" *-- "*" Puntos
Jugador "1" *-- "3" Vida
Paperboy "1" *-- "*" Periodico
Jugador "1" *-- "2" Habilidad
Juego "1" *-- "*" Nivel
Paperboy "1" o-- "*" TocarObstaculo


Habilidad <|-- Lanzar
Habilidad <|-- Velocidad


Nivel "1" *-- "1" Calle
Nivel "1" *-- "1" Sonido
Calle "1" *-- "*" Buzon
Calle "1" *-- "*" Alcantarilla
Calle "1" *-- "*" Casa
Calle "1" *-- "*" Perro
Calle "1" *-- "*" Charco
Casa "1" *-- "2" Ventana

Obstaculo <|-- Alcantarilla
Obstaculo <|-- Perro
Obstaculo <|-- Charco
TocarObstaculo o-- Obstaculo

Item <|-- Periodico
Lanzar o-- Periodico

class Paperboy
{
    -_Velocidad
    -frametime
    -currentFrame
    -numFrames
    -anchoFrame
    -altoFrame
    -_clock
    -_invulnerable
    -_tiempoInvulnerabilidad
    -_textura
    -_sprite

    +update
    +animacion
    +verificarColisiones
    +actualizarVulnerabilidad
}

class Sonido
{
    -_musicaFondo
    -_sonido

    +cargarMusicaFondo
}
class Periodico
{
    -_textura
    -_sprite
    -anchoVentana
    -altoVentana

    +respawn
    +update
    +draw
}
@enduml